#ifndef BATTLECITYCORE_GLOBAL_H
#define BATTLECITYCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BATTLECITYCORE_LIBRARY)
#  define BATTLECITYCORE_EXPORT Q_DECL_EXPORT
#else
#  define BATTLECITYCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // BATTLECITYCORE_GLOBAL_H
